import { CommonModule } from '@angular/common';
import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  inject,
  Input,
} from '@angular/core';
import { DashboardCount } from '../../../models/AppModels';
import { ChartModule } from 'primeng/chart';
import { RouterLink } from '@angular/router';
import { LoadingService } from '../../../services/loading.service';
import { AppService } from '../../../services/appService.service';
import { forkJoin, Subject, takeUntil } from 'rxjs';

@Component({
  selector: 'app-dashboard-admin',
  imports: [CommonModule, ChartModule, RouterLink],
  template: `
    <div class="w-full pt-10 pb-20 md:p-2">
      <div class="grid md:grid-cols-2 gap-4 h-[45%] md:px-10">
        <div class="flex flex-col gap-5">
          <div
            class="bg-gray-50 p-2 md:p-3 rounded-xl border border-gray-300 shadow-md flex flex-col"
          >
            <h3
              class="md:text-lg font-semibold mb-4 md:mb-3 text-blue-400 tracking-wider"
            >
              Quotations
            </h3>
            <div class="flex mb-4 gap-2">
              <div
                class="text-center p-2 rounded-md bg-[#FFB128] shadow-lg shadow-black/30 flex-1"
              >
                <div
                  class="text-4xl font-semibold text-white text-shadow-md tracking-widest"
                >
                  {{ dashboardCount.quotations.pending }}
                </div>
                <div
                  class="pt-2 text-xs text-white text-shadow-lg tracking-wider"
                >
                  Pending Approval
                </div>
              </div>
              <div
                class="text-center flex-1 p-2 rounded-md bg-[#36e72f] shadow-lg shadow-black/30"
              >
                <div
                  class="text-4xl font-semibold tracking-widest text-white text-shadow-lg"
                >
                  {{ dashboardCount.quotations.approved }}
                </div>
                <div
                  class="pt-2 text-xs text-white text-shadow-lg tracking-wider"
                >
                  Approved
                </div>
              </div>
              <div
                class="text-center flex-1 p-2 rounded-md bg-[#e72f2f] shadow-lg shadow-black/30"
              >
                <div
                  class="text-4xl font-semibold tracking-widest text-white text-shadow-lg"
                >
                  {{ dashboardCount.quotations.rejected }}
                </div>
                <div
                  class="pt-2 text-xs text-white text-shadow-lg tracking-wider"
                >
                  Rejected
                </div>
              </div>
            </div>
          </div>

          <div class="rounded-xl shadow-md flex flex-col">
            <div
              class="text-sm rounded-t-xl bg-blue-400 text-white text-shadow-md text-shadow-black/20 font-semibold tracking-widest px-4 py-3 border border-gray-200"
            >
              Quotes Generated By Day
            </div>
            <div
              class="bg-gray-50 px-4 flex-grow rounded-lg border py-2 border-white/10 flex items-center justify-center"
            >
              <p-chart
                type="line"
                [data]="quotationChartData"
                [options]="quotationChartOptions"
                style="width: 100%;"
              ></p-chart>
            </div>
          </div>
        </div>
        <div
          class="rounded-xl border border-gray-300 shadow-md flex flex-col items-center"
        >
          <h3
            class="text-lg font-semibold bg-pink-400 text-white tracking-widest text-shadow-md text-shadow-black/30 w-full text-center rounded-t-xl px-4 py-3"
          >
            Job Tracking
          </h3>
          <div
            class="bg-gray-50 rounded-b-xl pt-10 md:pt-0 flex flex-col gap-30 items-center justify-center w-full h-full"
          >
            <div class="relative w-40 h-40 flex items-center justify-center">
              <svg viewBox="0 0 36 36" class="absolute w-full h-full">
                <path
                  class="text-gray-700"
                  fill="none"
                  stroke="currentColor"
                  d="M18 2.0845a15.9155 15.9155 0 0 1 0 31.831"
                  stroke-width="4"
                  stroke-dasharray="100, 100"
                />
                <path
                  class="text-cyan-500"
                  fill="none"
                  stroke="currentColor"
                  d="M18 2.0845a15.9155 15.9155 0 0 1 0 31.831"
                  stroke-width="4"
                  stroke-dasharray="48, 100"
                  stroke-dashoffset="0"
                />
                <path
                  class="text-fuchsia-500"
                  fill="none"
                  stroke="currentColor"
                  d="M18 2.0845a15.9155 15.9155 0 0 1 0 31.831"
                  stroke-width="4"
                  stroke-dasharray="12, 100"
                  stroke-dashoffset="-48"
                />
              </svg>
              <div class="absolute text-5xl font-bold">
                {{ dashboardCount.jobs.active }}
              </div>
            </div>
            <div class="flex justify-around w-full text-sm pb-2">
              <div class="text-center">
                <div
                  class="w-2 h-2 rounded-full bg-cyan-500 inline-block mr-1"
                ></div>
                <span class="text-gray-400">Active Jobs</span>
              </div>
              <div class="text-center">
                <div
                  class="w-2 h-2 rounded-full bg-fuchsia-500 inline-block mr-1"
                ></div>
                <span class="text-gray-400">Delayed Jobs</span>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="grid md:grid-cols-2 gap-4 h-[50%] md:px-10 mt-3">
        <div
          class="bg-gray-50 rounded-xl border border-gray-300 shadow-md flex flex-col"
        >
          <h3
            class="text-lg px-4 py-2 rounded-t-xl font-semibold mb-3 bg-cyan-400 text-white text-shadow-lg"
          >
            Job Tracking
          </h3>
          <div class="flex space-x-8 p-4">
            <div class="text-center flex-1 border-r border-gray-300">
              <div class="text-4xl font-semibold tracking-widest text-gray-600">
                {{ dashboardCount.jobs.active }}
              </div>
              <div class="text-sm text-gray-400">Active Jobs</div>
            </div>
            <div class="text-center flex-1">
              <div
                class="text-4xl font-semibold tracking-widest text-yellow-400"
              >
                {{ dashboardCount.jobs.pending }}
              </div>
              <div class="text-sm text-gray-400">Pending</div>
            </div>
            <div class="text-center flex-1 border-l border-gray-300">
              <div class="text-4xl font-semibold tracking-widest text-red-400">
                {{ dashboardCount.jobs.delayed }}
              </div>
              <div class="text-sm text-gray-400">Delayed</div>
            </div>
          </div>
          <div class="p-4">
            <div class="text-sm text-gray-700 tracking-wider">Latest Job</div>
            <div class="mt-2 flex flex-row items-center gap-2">
              <i class="pi pi-circle-on !text-[5px]"></i>
              <div class="text-xs text-gray-500 tracking-wider">
                Job 1 in progress
              </div>
            </div>
          </div>
          <div class="px-4 pb-4">
            <div class="border-b border-gray-200"></div>
          </div>
          <div class="flex justify-center px-4 pb-4 gap-3">
            <button
              [routerLink]="'/quotation/form'"
              class="px-5 py-2 text-gray-700 text-sm tracking-wider border-[#40A0AC] border-2 cursor-pointer rounded-md font-semibold transition duration-200 hover:bg-cyan-200"
            >
              Create New Quote
            </button>
            <button
              class="cursor-pointer px-5 py-3 text-sm tracking-wider bg-gray-200 hover:bg-gray-300 rounded-md transition duration-200"
            >
              View Reports
            </button>
          </div>
        </div>

        <div
          class="bg-gray-50 rounded-xl border border-gray-300 shadow-md flex flex-col"
        >
          <h3
            class="px-4 py-3 shadow-sm rounded-t-xl text-lg font-semibold mb-3 text-white text-shadow-lg bg-yellow-400"
          >
            Work Orders (WO)
          </h3>
          <div class="flex justify-between p-4">
            <div>
              <div class="text-2xl font-semibold tracking-widest text-gray-700">
                323.95
              </div>
              <div class="text-sm text-gray-400">Personnel Working ($)</div>
            </div>
            <div>
              <div class="text-2xl font-semibold tracking-widest text-gray-700">
                18,903.38
              </div>
              <div class="text-sm text-gray-400">Total Material Cost ($)</div>
            </div>
          </div>
          <div class="px-4 pb-4 flex-grow">
            <div
              class="w-full h-full bg-gray-200 rounded-lg border border-white/10 p-2 flex items-center justify-center"
            >
              <span class="text-gray-500 text-xs"
                >Work Order Chart Placeholder</span
              >
            </div>
          </div>
        </div>
      </div>
    </div>
  `,
  styleUrl: './dashboard-admin.less',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DashboardAdmin {
  @Input() dashboardCount: DashboardCount = {
    quotations: { pending: 0, approved: 0, rejected: 0 },
    jobs: { active: 0, pending: 0, delayed: 0 },
    workOrders: 0,
  };

  @Input() quotationChartData: any;
  @Input() quotationChartOptions: any;

  private readonly loadingService = inject(LoadingService);
  private readonly appService = inject(AppService);
  private readonly cdr = inject(ChangeDetectorRef);
  protected ngUnsubscribe: Subject<void> = new Subject<void>();

  isMobile = window.innerWidth < 770;
  notifications: { message: string; time: Date }[] = [];

  ngOnInit(): void {
    const requests: any = {
      dashboardCount: this.appService.GetDashboardCount(),
      quotationChart: this.appService.QuotationChart(),
    };

    forkJoin(requests)
      .pipe(takeUntil(this.ngUnsubscribe))
      .subscribe({
        next: (res: any) => {
          this.dashboardCount = res.dashboardCount;

          if (!this.isMobile) {
            this.notifications = res.notifications;
          }

          // 🆕 Handle quotation chart data
          const chartData = res.quotationChart || [];
          const labels = chartData.map((item: any) =>
            new Date(item.date).toLocaleDateString('en-MY', {
              day: '2-digit',
              month: 'short',
            })
          );
          const data = chartData.map((item: any) => item.count);

          this.quotationChartData = {
            labels,
            datasets: [
              {
                data,
                borderColor: '#42A5F5',
                tension: 0.4,
                fill: false,
              },
            ],
          };

          this.quotationChartOptions = {
            plugins: {
              legend: { display: false },
            },
            scales: {
              x: {
                ticks: { color: '#A0AEC0' },
                grid: { color: 'rgba(255,255,255,0.1)' },
              },
              y: {
                ticks: {
                  color: '#A0AEC0',
                  precision: 0,
                  callback: function (value: number) {
                    return Math.floor(value);
                  },
                },
                grid: { color: 'rgba(255,255,255,0.1)' },
              },
            },
          };

          this.cdr.detectChanges();
        },
        error: (err) => {
          console.error(err);
          this.loadingService.stop();
        },
        complete: () => {
          this.loadingService.stop();
        },
      });
  }
}
